# 测试套件元数据
test_suite:
  name: "射频基础测试套件"
  version: 1.2
  description: "包含射频设备基础功能验证用例"

# 测试用例序列
test_cases:
  - id: GPON-2024
    name: "GPON ABC型号认证测试"
    test_class: "test_cases.gpon.GPon_abc_TC.GPonTestCase"
    instrument:
      type: gpon  # 仪器类型标识符
      config:  # 仪器专属配置
        port: COM3
        baudrate: 115200
    parameters:
      tx_power: [-5.0, 5.0]
      rx_sensitivity: -30.0

# 设备配置（可选）
instrument_config:
  resource_name: "TCPIP0::192.168.1.100::inst0::INSTR"  # VISA资源地址
  timeout: 5000  # 毫秒
