# 测试套件元数据
test_suite:
  name: "射频基础测试套件"
  version: 1.2
  description: "包含射频设备基础功能验证用例"

# 测试用例序列
test_cases:
  - test_case_id: "TC001"
    test_case_name: "登录设备"
    test_class: "test_cases.login_test.LoginTestCase"
    test_steps:
      - step_id: "STEP001"
        step_name: "登录设备"
        action: "dut.login"
        expect: "success_prompts"
        
dut_config:
  # type: telnet
  # config:
  type: telnet  # 通信协议标识符
  host: "192.168.0.1"
  port: 23
  username: root  # 必须配置
  password: ADTN12345678  # 必须配置
  timeout: 5000  # 毫秒
  login_prompts: 
    - "(?i)tc login:"  # 支持多个匹配模式
    - "login:"
  password_prompts: 
    - "(?i)Password:"
  success_prompts:  # 新增成功提示符配置
    - "<H3C>"
    - "#"
    - "\\$"  # 支持正则表达式

# instrument_config:
#   type: gpon  # 仪器类型标识符
#   config:  # 仪器专属配置
#     port: COM3
#     baudrate: 115200

